.gitignore, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, .vscodeignore, package-lock.json, package.json, src/bazel/commands.ts, src/bazel/query.ts, src/extension/extension.ts, src/workspace-tree/workspace-tree.ts, tsconfig.json
As I started working to integrate the debugger, I realized I needed some kind of UI to trigger builds off of, so I added a first version of a tree view that shows packages/targets (screenshot below). Clicking on a target opens the BUILD file and places the cursor on the line/column where the target is defined.
I imagine that eventually we may want to have other views, like quick input view where the user can use the keyboard exclusively to fire off builds of frequently used targets, but this is a relatively easy first step.
This PR also lays down some common components for executing Bazel commands. The query functionality uses a mode where we execute it as a child process and interpret its stdout, but future build/test commands may want to hook up an integrated terminal or other debug …
=> Add a Bazel target tree view to the explorer.

package.json, src/bazel/commands.ts, src/extension/extension.ts, src/workspace-tree/workspace-tree.ts
This adds "Build Target" as a menu item for all targets, and "Test Target" to
targets whose rule names end in "_test".
=> Add context menu items to the workspace tree.

package-lock.json
This backs us off event-stream 3.3.6, which added a dependency on
flatmap-stream which contained malicious code (see
https://github.com/dominictarr/event-stream/issues/116). Our
dependency was locked to a version of flatmap-stream that does not
seem to have been affected, but this removes the dependency entirely
to be safe.
=> Update package-lock.json to remove security vulnerability.

src/extension/extension.ts
Without this change, trying to dismiss it without a selection causes it
to continue recursing and asking for a selection.
=> Fix cancellation of the quick picker.

src/codelens/bazel_build_code_lens_provider.ts, src/extension/extension.ts
In addition to updating on file changes, we clear out the lenses when a
file is being edited (i.e., dirty). This is because the lenses don't
automatically move with edits (a more robust language server would be
needed to handle this), and we can't accurately determine the build
targets in an edited BUILD file until it's been saved and we can run the
query again.
=> Watch BUILD files for changes to refresh CodeLenses.

package.json
This ensures that they show up in the command palette like "Bazel: Build
Target" instead of just "Build Target".
=> Add category strings to Bazel commands.

src/codelens/bazel_build_code_lens_provider.ts
This was causing "Build [object Object]" to show up instead of the target name.
=> Fix CodeLens titles after switching to query protos.

src/bazel/bazel_utils.ts, src/codelens/bazel_build_code_lens_provider.ts, src/extension/extension.ts, src/symbols/bazel_build_symbol_provider.ts, src/symbols/bazel_target_symbol_provider.ts, src/symbols/index.ts
Provide a [Go to symbol](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol) capability for navigating rules within a BUILD file
=> Symbol provider for bazel rules

src/buildifier/buildifier.ts
bazelbuild/buildtools#453 could get fixed in making the default for formatting
be to not do anything if a --lint mode is enabled, so be explicit about wanting
fix mode for formatting just to be safe.
=> Explicitly use --mode=fix

.vscode/launch.json, src/debug-adapter/client.ts, src/debug-adapter/connection.ts
- Handle file paths correctly for breakpoints.
- Don't cause an exception if the debugger tries to get the frames of an unpaused thread.
- Don't drop events when the sequence number is a Long zero.
Fixes #24.
=> Various debugger fixes.

src/bazel/tasks.ts
Previously `createBazelTask` was using "Configuration variables", which by default was an empty string.
Fix #63
=> Fix task default executable path

src/extension/extension.ts
https://docs.bazel.build/versions/master/external.html#depending-on-non-bazel-projects
Add formatting support for *.BUILD build files. Particularly useful for depending on non-Bazel projects.
=> Add *.BUILD formatting

src/bazel/bazel_query.ts, src/bazel/bazel_quickpick.ts, src/workspace-tree/bazel_workspace_folder_tree_item.ts
- Always sort the result (callers were).
- Tweak the query so packages that are created by an empty BUILD file still
get captured (done by using a query that catches the BUILD file target
itself (it is exposed as a source file))
Fixes #79
=> Improvements to package queries.

src/bazel/bazel_workspace_info.ts, src/workspace-tree/bazel_workspace_folder_tree_item.ts
The getBazelWorkspaceFolder() function would hang if the loop reached the base directory without encountering a WORKSPACE file. Fixed and tested it on MacOS. In addition, since I suspect this fix won't work for Windows (the base directory is probably different) I added a failsafe for other file systems.
This fix also exposed a problem in getDirectoryItems() if the workspace does not exist. Added the fix for that too.
=> Fixed an issue where the extension would hang on non-workspace directories.

package.json, src/extension/extension.ts, src/logging/index.ts, src/logging/logging.ts
Creates a logging output channel called "VSCode-Bazel". Components can then log to this channel to show debug information.
Adds a new command: "Show Extension Log" which will display the channel.
Also adds a new settings: "bazel. showExtensionLog" which will automatically display the output channel when the plugin initializes.
=> Add logging output channel

src/bazel/bazel_command.ts, src/bazel/bazel_query.ts, src/bazel/bazel_quickpick.ts, src/bazel/bazel_utils.ts, src/bazel/tasks.ts, src/codelens/bazel_build_code_lens_provider.ts, src/extension/configuration.ts, src/extension/extension.ts, src/symbols/bazel_target_symbol_provider.ts, src/workspace-tree/bazel_package_tree_item.ts, src/workspace-tree/bazel_workspace_folder_tree_item.ts
bazel_command currently has a dependency on vscode for the Bazel executable path. This change is to remove that dependency by passing the executable path into the constructor of the BazelCommand class.
This has the following benefits:
1. This will allow us to eventually move the Bazel-specific logic into a separate library.
2. It makes the code more testable.
=> Remove vscode dependency from bazel_command

.bazelci/presubmit.yml
Looking at `npm help clean-install` it seems like CI setups are better off
using it (vs. `install`) because it won't try to update the package json
files.
=> Use `npm clean-install` for CI.

README.md, package.json
Inspired by #57, make it clear that the command is about the Starlark Debugger
and not more general "debugging" (-c dbg) that Bazel supports.
=> Rename the command to include "Starlark Debugger"

src/workspace-tree/bazel_workspace_tree_provider.ts
We try to create a `BazelWorkspaceFolderTreeItem` for every folder the user has opened regardless of whether those folders are Bazel WORKSPACE folders.
This fix will ignore non-Bazel folders when creating
`BazelWorkspaceFolderTreeItem`s.
=> Fix error when user has multiple workspace folders open

package-lock.json, package.json
This is needed for remote-extension-safe clipboard APIs; see
https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-clipboard.
=> Update vscode dependency to ^1.30.

src/extension/extension.ts
If users have other starlark-ish files to format that don't meet the patterns here, there's no way to take advantage of the formatter. This enables using a file association in the workspace/user settings to format anything set as "starlark".
=> Add "starlark" language to formatting provider.

src/buildifier/buildifier.ts
Adjust code to match original intent. `pathObject` properties `base` and `ext` have values like "BUILD.bazel" and ".bazel", respectively. For the comparisons here, we want the results of `path.basename()` with its `ext` parameter set.
Fixes https://github.com/bazelbuild/vscode-bazel/issues/125.
=> Fix buildifier file type detection

src/codelens/bazel_build_code_lens_provider.ts, src/symbols/bazel_target_symbol_provider.ts
These both triggered on BUILD files meaning you always got two alerts every
time, and you can't just ignore them, they happen every time you open a matching
file not in a workspace so they sorta get spammy.
Fixes #136
=> Drop the warnings when a file isn't in a WORKSPACE.

package.json, src/bazel/bazellib/bazel_utils.ts
Mainly useful as a global setting (not per project), lets you disable some
WORKSPACE discovery/target treeview where but still support the other features
(buildifer, BUILD syntax support, etc.).
=> Add a setting to support disabling the building support.

package-lock.json, package.json
This doesn't move things to new major versions, just does the minor versions.
```
$ npm outdated
Package               Current  Wanted   Latest  Location
@types/node            6.14.6  6.14.8  12.11.7  vscode-bazel
tslint                 5.16.0  5.20.0   5.20.0  vscode-bazel
typescript              3.4.5   3.6.4    3.6.4  vscode-bazel
vscode                 1.1.33  1.1.36   1.1.36  vscode-bazel
vscode-debugadapter    1.34.0  1.37.1   1.37.1  vscode-bazel
vscode-debugprotocol   1.34.0  1.37.0   1.37.0  vscode-bazel
which                   1.3.1   1.3.1    2.0.1  vscode-bazel
$ npm update
+ vscode-debugadapter@1.37.1
+ vscode-debugprotocol@1.37.0
+ vscode@1.1.36
+ tslint@5.20.0
+ @types/node@6.14.8
+ typescript@3.6.4
added 3 packages from 2 contributors, removed 4 packages, updated 33 …
```
=> Update the dependencies.

package.json, src/bazel/bazellib/bazel_utils.ts
Should make it easier if needing more than one thing.
The VSCode docs didn't seem to document this, but the UI supports it and other
extensions use it.
=> Change pathsToIgnore to be a list.

package.json, src/bazel/tasks.ts, src/extension/extension.ts
They follow the normal vscode support, they could be per directory, workspace,
or user.
Fixes #134
=> Add settings for startup options and command args.

src/bazel/bazellib/bazel_utils.ts
Looks like all the queries in extension.ts already was using double quotes
for this, and only this one was trying to use single quotes. It appears the
single quotes relied on the shell to handle them to make things work.
Fixes #153
=> Use doublequotes to support Windows.

.vscodeignore
Since the extension isn't a webpack, I think this is still needed.
=> Include node_modules.

package.json, src/bazel/bazel_command.ts
Developers might need bazel options enabled to get the targets they want
defined, so also support startup options in the queries.
=> Support startup options in all queries.

package.json, src/bazel/bazel_command.ts, src/bazel/bazel_query.ts
By default, move all queries over to a custom --output_base. This keep the
bazel lock from interfering with user done builds/ibazel/etc.
Helps with #75.
=> Make queries use --output_base.

src/bazel/bazel_quickpick.ts, src/bazel/bazel_workspace_info.ts
If there is only one workspace folder, just show the picks for the part of
the tree. If there is >1 workspace folder, first ask them which workspace
folder and then ask them which targets. The workspace selection models what
was already being done for 'clean'.
Somewhat addresses #133
Fixes #83
=> Make the quickpick use the same root(s) as the tree view.

package.json, src/workspace-tree/bazel_workspace_tree_provider.ts
The "refresh" command is left enabled in the palette to support a developer
adding files such that it becomes a Bazel workspace or for them to add
another folder to an existing code-workspace and that new folder containing
a Bazel workspace.
Fixes #144
=> Enabled/disable command and TreeView based on having a bazel workspace.

src/bazel/bazel_utils.ts
I noticed that workspaces with workspace files named `WORKSPACE.bazel` are not recognised as workspace root.
The patch is compile-tested only.
=> Also discover WORKSPACE.bazel as workspace root

package.json
While it likely makes more sense to users to set this on the app level so can
apply at scale, I've recently had a few use cases where it would be useful to
stick "." in here to on a project level just to disable this extension for this
one case and that's far easier than making a regex for the specific one off
path.
=> Allow pathsToIgnore to be set on the workspace level.

package.json, src/codelens/bazel_build_code_lens_provider.ts
Based on allevato's comment on the issue, this default is to disable the
CodeLens and folks have to opt into it instead.
Fixes #187
=> Add an option to control the enabling of the CodeLens.

package.json, syntaxes/starlark.tmLanguage.json
This synchronizes the fileTypes in the syntax (which is more correct and helps those trying to use the syntax outside of VS Code) with those indicated in package.json
Note: In the case of `BUILD`, for example, which is not an extension, modern interpreters for tmLanguage support non-extension filenames here per https://forum.sublimetext.com/t/tmlanguage-and-filename-patterns/383
=> syntaxes: synchronize fileTypes with those indicated in package.json

.vscode/settings.json
I was looking to contribute and my default settings for vscode were using a different formatter than the one it looks like this project requires. I also noticed that the formatting in the repository is using trailing commas so I enabled that setting with on prettier.
=> Updated .vscode/settings.json format settings

.bazelci/presubmit.yml, BUILD, WORKSPACE
This commit fixes #269, which was caused by bazelbuild/continuous-integration#1331
Some context:
Our CI infra expects all projects to be buildable with Bazel, i.e. there must be a WORKSPACE file and at least one BUILD file.
This project did not meet this requirement, but we still wanted to have it on CI to run some npm commands. Someone came up with a workaround:
Let's create dummy WORKSPACE and BUILD files during setup ("shell_commands").
However, this stopped working because bazelbuild/continuous-integration#1331 changed the CI infra to run `bazel info` before executing the shell commands, which then failed because there was no Bazel workspace yet.
Eventually we should make this project buildable and testable with Bazel.
=> Add dummy BUILD and WORKSPACE files to fix CI

package-lock.json
Any other changes to packages.json adds a downgrade (for some reason) to
path-parse 1.0.6 to the packages-lock.json. That's not ideal and, on top
of that, 1.0.6 has a vulnerability in it.
https://github.com/advisories/GHSA-hj48-42vr-x3v9
To prevent that from happening, we upgrade to 1.0.7 explicitly in the
lockfile.
=> upgrade path-parse explicitly

src/buildifier/buildifier.ts
I noticed that the vscode extension's outputs for copybara configuration files are different from the CLI's output.
`getBuildifierFileType` is out of sync with <https://github.com/bazelbuild/buildtools/blob/a43aed7014c840a4c20c84958f3f15df5da780f5/build/lex.go#L125-L151>
- https://github.com/bazelbuild/buildtools/pull/560
- [getBuildifierFileType](https://github.com/bazelbuild/vscode-bazel/blob/ffd1450a4222825db11533aac5f5c7aa51ef50eb/src/buildifier/buildifier.ts#L116-L152)
=> return `default` for .sky files in getBuildifierFileType

package.json, src/bazel/bazel_cquery.ts, src/bazel/bazel_info.ts, src/bazel/bazel_query.ts, src/bazel/bazel_quickpick.ts, src/bazel/bazel_utils.ts, src/bazel/bazel_workspace_info.ts, src/definition/bazel_goto_definition_provider.ts, src/extension/extension.ts, src/workspace-tree/bazel_package_tree_item.ts, src/workspace-tree/bazel_workspace_folder_tree_item.ts
This command can be used in launch configurations to obtain the path to an executable built by Bazel. For example, you can set the "program" attribute of a launch configuration to an input variable:
"program": "${input:binaryOutputLocation}"
Then define a command input variable:
"inputs" [
{
"id": "binaryOutputLocation",
"type": "command",
"command": "bazel.getOutputTarget",
"args": ["//my/binary:target"],
}
]
Addresses https://github.com/bazelbuild/vscode-bazel/issues/273 and could form the basis of https://github.com/bazelbuild/vscode-bazel/issues/217, https://github.com/bazelbuild/vscode-bazel/issues/207, and https://github.com/bazelbuild/vscode-bazel/issues/115.
=> Add bazel.getTargetOutput command

CHANGELOG.md, src/extension/extension.ts
There is a minor transposition that needs to be fixed in the example and a missing : It should be:
"inputs": [
{
"id": "binaryOutputLocation",
"type": "command",
"command": "bazel.getTargetOutput",
"args": ["//my/binary:target"],
}
]
bazel.getOutputTarget -> getTargetOutput and inputs needs a :
=> fixes minor transpositiion in example for new bazel.getTargetOutput

scripts/build.sh
It runs as an npm script, and npm puts the appropriate bin directory on the path. So there's no need to provide relative paths or chmod stuff.
=> Simplify build.sh

package.json, src/extension/extension.ts, syntaxes/starlark.tmLanguage.json
With the addition of `MODULE.bazel` to the mix, it seems to make sense to match all files with this extension.
=> Expand matching files to *.bazel

src/extension/extension.ts
I missed testing this case with command input variables in #275. IMO it's a VSCode bug that the calling convention is different than with `vscode.commands.executeCommand` (https://github.com/microsoft/vscode/issues/167970), but nevertheless we need to handle it.
=> Fix and document providing flags to `getTargetOutput`

package.json
> `machine-overridable` - Machine specific settings that can be overridden by workspace or folder settings.
- https://code.visualstudio.com/api/references/contribution-points
Organizations may install these binaries to a known path which can be specified in shared workspace settings.
Fixes https://github.com/bazelbuild/vscode-bazel/issues/236.
=> Make executable and buildifierExecutable settings `machine-overridable`

package.json, src/extension/extension.ts
I proposed these originally in https://github.com/bazelbuild/vscode-bazel/issues/273 as an initial idea for what became https://github.com/bazelbuild/vscode-bazel/pull/275. But I have encountered another use case that makes me think they are generally useful:
When [debugging on macOS](https://github.com/bazelbuild/bazel/issues/6327#issuecomment-982965782), lldb needs to be configured with the command `platform settings -w $execution_root`, where `$execution_root` is what's returned by `bazel info execution_root`. With `bazel.info.*` commands, you can create a launch configuration that contains:
```
"initCommands": [
"platform settings -w ${command:bazel.info.execution_root}",
]
```
=> Add bazel.info.* commands

package.json, src/bazel/bazel_query.ts
Adds an outputBase string configuration that changes where output_base is placed. This is convenient for when someone wants bazel using something other than TMPDIR. This is useful if you use a ramdisk for faster builds, or if your TMPDIR has space or security constraints.
=> make output_base directory configurable

package.json, src/bazel/tasks.ts, src/extension/extension.ts
This implementation doesn't support to pass arguments for the `blaze run //path:taget` command, but it can be implemented in the following changes.
=> Add a new command to run targets without arguments

.bazelci/presubmit.yml
Fixes deprecation warnings and failures in CI. See for example, https://buildkite.com/bazel/vscode-bazel-vs-bazel/builds/1993#018c22c3-eae0-4d53-96c8-7c3afe453424.
=> Update CI to Ubuntu 20 and Node 20

src/bazel/bazel_query.ts
I spent a little bit of time digging into why this extension kept
crashing in our codebase. After some investigation, I noticed the bazel
query helper requests the output as protobufs. The output is very useful
for tools, but it does come with a few default options that bloat the
query's output:
* `--proto:locations=true`: Whether to output location information in
proto output at all.
* `--proto:output_rule_attrs="all"`: Comma separated list of attributes
to include in output.
* `--proto:rule_inputs_and_outputs=true`: Whether or not to populate the
rule_input and rule_output fields.
* `--proto:default_values=true`: If true, attributes whose value is not
explicitly specified in the BUILD file are included; otherwise they are
omitted.
I dug through the codebase and it seems like _none_ of …
=> perf: reduces bazel query output

src/completion-provider/bazel_completion_provider.ts
This change fixes a bug where the target completion doesn't work when the target name is not quoted (like inside `$(location)`).
Fixes #304
=> Fix candidate target name parsing for completion

src/bazel/bazel_query.ts
I believe https://github.com/bazelbuild/vscode-bazel/pull/308 (shipped with v0.8.0) introduced a regression in the query output that results to the following bugs (see [screencast](https://github.com/bazelbuild/vscode-bazel/assets/13268391/e58b4839-34d0-4246-9d6c-ffe887ad1cd9)):
* Clicking on the targets in Bazel Build Targets no longer works.
* CodeLens feature that allows navigating to a target no longer works.
* The tooltips for build command now all shows at the top of the BUILD file instead of being inline with the targets.
Fix https://github.com/bazelbuild/vscode-bazel/issues/319
cc @iamricard
=> Fix query output for target location

src/bazel/bazel_command.ts
Bazel 7 [enables bzlmod](https://bazel.build/about/roadmap#bzlmod_external_dependency_management_system) by default which results to the automatic generation of `MODULE.bazel` files when the extension runs bazel command in the background.
From a VSCode extension standpoint, it's a bad UX (IMO) to create new files unintentionally. If Bazel wants to enforce having `MODULE.bazel` files moving forward, that is already covered when users run Bazel commands locally.
In the future, we can gate this flag behind a boolean config when bzlmod is fully supported https://github.com/bazelbuild/vscode-bazel/issues/294.
=> Prevent automatic MODULE.bazel file creation

src/bazel/bazel_query.ts
The location of this URL has changed, so this updates it to the new location.
=> Update dead URL

CODEOWNERS
Per https://github.com/bazelbuild/vscode-bazel/issues/241#issuecomment-1900405902. Thank you for offering!
I think there's a second step that I don't have permission to do, which is to add @cameron-martin as a collaborator with write access. At least that's what GitHub is telling me:
=> Add @cameron-martin to CODEOWNERS

.vscode/settings.json
Previously this set the formatter to eslint for all languages, but eslint only works for javascript and typescript.
Fixes #255
=> Scope eslint formatter to typescript in vscode settings

.bazelrc
This prevents the creation of `MODULE.bazel` and `MODULE.bazel.lock` in this repository after running bazel, for example as happens automatically by this plugin after opening starlark files.
=> Disable bzlmod

package.json
When running `vsce package`, it complains that the versions of `engines.vscode` and `@types/vscode` are incompatible. This updates `engines.vscode` to match the version of `@types/vscode`.
=> Increase vscode engine version

package.json
So far, the `bazelWorkspace` view, listing the available build targets,
was only shown after running the first Bazel command, e.g., through
the command pallete. This behavior was probably unintended and is rather
cumbersome for people which want to inspect the available Bazel targets.
The chain of events which lead to this behavior are:
* The `bazelWorkspace` view is only shown when the
`vscodeBazelHaveBazelWorkspace` context variable is set.
* This context variable is unset by default, and hence the view is
hidden initially.
* As soon as the first Bazel command is run from the command pallete,
the extension was activated.
* As part of activating, the extension detected that there is in fact
a Bazel workspace and hence it set the `vscodeBazelHaveBazelWorkspace`
context variable, unhiding …
=> Activate the extension automatically

package.json, src/extension/extension.ts, src/workspace-tree/bazel_workspace_tree_provider.ts
This commit hides the "Restart LSP" command from the Command Palette if the LSP is disabled. Otherwise, trying to use the "Restart LSP" command without any LSP being configured leads to a user-visible error.
As part of this, I also renamed `vscodeBazelHaveBazelWorkspace` to `bazel.haveWorkspace` such that the context variables all share a common `bazel.*` prefix.
=> Enable the "Restart LSP" command only if a LSP is configured

package.json
The commands `bazel.info.*` and `bazel.getOutputPath` are intended to be used as command variables within `launch.json` and `task.json`. For additional context, see  #273, #275 and #291.
Those commands are not intended to be called by users directly. As such, they should not show up in the command palette. Calling them from the command picker has no user-visible effect and leaves the user with the impression that those commands would be broken.
This commit removes them from the `commands` contribution point, thereby hiding them from the command picker. To make sure that the extension is loaded as soon as some `task.json`/`launch.json` invokes any of those commands, they now need to be registered as `activationEvents`, since VS Code will no longer discover those events automatically from …
=> Hide commands intended as command variables

src/extension/command_variables.ts, src/extension/extension.ts
This commit moves all the commands intended to be used as "comand variables" from the `extension.ts` into a new `command_variables.ts` file. This is a precursory refactoring before introducing additional command variables.
=> Refactoring: Move commands into a `command_variables.ts`

package.json, src/extension/command_variables.ts
Not sure why this wasn't added initially in #291. Maybe the assumption was that the workspace root is already available through VS Code's `${workspaceFolder}`. However, that represents the place where VS Code was opened. The Bazel workspace folder might be further up in the directory tree.
=> Add `bazel.info.workspace` command variable

README.md, package.json, src/bazel/bazel_task_info.ts, src/bazel/tasks.ts, src/extension/extension.ts
User-facing changes
-------------------
This commit fixes two user-facing bugs:
* The "Run Task" command provides a list of recently used tasks. This list also contains the build/test tasks started from the "Bazel Build Targets" tree view. However, trying to rerun any of those tasks resulted in an error message.
* The extension already contributed a `taskDefinition` for bazel tasks. However, trying to actually define such a task in the `tasks.json` resulted in the same error message.
In both cases, the user was presented with the error message
> There is no task provider registered for tasks of type "bazel"
This commit fixes the issue, such that rerunning tasks from the history and configuring tasks through `tasks.json` now works properly.
Furthermore, the `taskDefinition` inside the …
=> Support `bazel` tasks from `tasks.json`

package.json
This reverts commit 64c9d7eb41bed5a3b9ab67a6423f1f7eee56ed65.
The underlying issue that this addresses is now fixed in Bazel 7.1.0. See #216 and https://github.com/bazelbuild/bazel/pull/21505.
=> Revert "Make queries share the same server by default (#270)"

src/bazel/bazel_query.ts, src/buildifier/buildifier_format_provider.ts, src/workspace-tree/bazel_package_tree_item.ts, src/workspace-tree/bazel_target_tree_item.ts, src/workspace-tree/bazel_workspace_folder_tree_item.ts, src/workspace-tree/icons.ts, tsconfig.json
This commit makes the TypeScript configuration stricter by enabling the `strict` setting. This implies that the `alwaysStrict` setting is implicitely enabled and no longer needs to be mentioned explicitly.
This required three fixes:
* in `icons.ts`, `SPECIFIC_RULE_CLASS_ICONS` needed an explicit type
* in `bazel_query.ts`, `execOptions` needed an explicit type
* All usages of `blaze_query.Target` had to be replaced by `ITarget`. This was necessary, because `queryResult.target` is of type `ITarget[]` not `Target` and `bazel_{package,target}_tree_item.ts` would not have compiled otherwise.
The `strictNullChecks` setting is explicitly opted-out. There are 117 violations against those stricter null checks, and to make the reviews easier, I plan to fix those in a separate commit.
I also …
=> Stricter typescript configuration

package.json, src/buildifier/buildifier.ts
This PR adds the `buildifierConfigJsonPath` setting, which allows a custom path to be set to pull the json configuration file for `buildifier` (this is often `.buildifier.json`). If the `buildifierConfigJsonPath` path is set, when `buildifier` is run within this extension, the `--config <path>` CLI arguments will be passed to `buildifier`.
While it could be said that this PR is now adding support for the `.buildifier.json` file -- it's only adding support for the customization of that file path. https://github.com/bazelbuild/vscode-bazel/pull/350 actually pulled out yet another drive-by fix (of https://github.com/bazelbuild/vscode-bazel/issues/208) by adding the working directory. In that PR, `cwd: vscode.workspace.workspaceFolders?.[0]?.uri?.fsPath` is setting the working directory for …
=> Add `buildifier` Json File Configuration

tsconfig.json
As part of #358, I removed the `allowJs` setting from the `tsconfig.json`. I didn't know why we needed `allowJs` and everything seemed to still work smoothly.
However, when trying to build the extension from a completely fresh git checkout, I realized that the `protos.js` file was missing from the `out` directory. With `allowJs: false` the `src/protos/protos.js` file was no longer copied to the `out` directory. This only worked locally for me, because the current build is not hermetic.
=> Fix protobuffers build by re-enabling `allowJs`

README.md, package.json, src/assert.ts, src/bazel/bazel_quickpick.ts, src/completion-provider/bazel_completion_provider.ts, src/extension/command_variables.ts, src/extension/extension.ts
This commit introduces the `bazel.pickTarget` and `bazel.pickPackage` command variables. Those commands can be used from `tasks.json` and `launch.json` to prompt the user to select a Bazel target or package. The available choices are determined by a user-specified Bazel query.
The implementation reuses the existing quick-pick functionality from `bazel_quickpick.ts`. The `wrapQuickPick` function parses the arguments passed from the `task.json` and then forwards to the existing quickpicks.
Those utility functions were restructured as part of this commit:
1. The internal helpers `queryWorkspaceQuickPickPackages` and `queryWorkspaceQuickPickTargets` were inlined into `queryQuickPick{Packages,Targets}` as the internal helper functions got in the way of other changes, but didn't deduplicate any …
=> feat: Introduce `pickTarget` and `pickPackage` command variables

CONTRIBUTING.md
This commit documents that commits should use Convenctional Commit messages, such that release-please picks up the release notes correctly.
=> ci: Ask contributors to use Conventional Commit messages

eslint.config.js, package-lock.json, package.json
This commit updates typescript, eslint and the eslint plugins to the latest versions.
Also, this commit migrates from `.eslintrc.js` to `eslint.config.js`. `.eslintrc.js` will be deprecated in ESLint 9.0. This commit migrates to `eslint.config.js` in anticipation of this change. Doing so also has the benefit that the config is more self-contained now and no longer depends on parameters passed in from the `package.json`.
=> build: Update toolchain

src/extension/extension.ts
Otherwise, VS Code would assume the extension to not be properly activated until the user closed the "Buildifier not found" notification. And as long as the extension activation did not finish, there was a never-finishing "Loading" indicator on top of the "Bazel Build Targets" tree view.
=> fix: Don't wait on the "Buildifier not found" notification

eslint.config.js, package-lock.json, package.json, src/bazel/bazel_workspace_info.ts, src/buildifier/buildifier.ts, src/debug-adapter/connection.ts, src/extension/extension.ts, tsconfig.json
In #363, I accidentally disabled all eslint checks: I used `eslint` and thought this would actually run the linter on the complete source tree. Starting from ESLint 9.0, this will actually work (See https://eslint.org/blog/2024/04/eslint-v9.0.0-released/#running-eslint-with-no-file-arguments). But for ESLint 8.x, we still need to use `eslint .`
This commit fixes that oversight in `package.json` and rectifies all the fall-out from this mistake.
First, I finished the migration to the new eslint.config.js format. To avoid further bugs, I first enabled TypeScript's type checking via `@ts-check`. I then followed the migration guide from https://eslint.org/docs/latest/use/configure/migration-guide to fix the config in general.
Doing so, I changed a the linter config in the following way:
* I …
=> ci: Fix eslint integration

README.md, package.json, src/extension/extension.ts
Previously the docs suggested using facebook's proof-of-concept bazel language server, but there is a more up-to-date version available based on this. There is also another implementation, starpls, that is based on rust-analyzer. This also updates the default values of the lsp settings to not favour a particular language server.
=> docs: Update options for language servers

README.md, package.json
This flips the `bazel.queriesShareServer` default back to `true`, since I think it was a bit hasty in #355 to break everyone not on the latest bazel version. Instead, I have added a section to the docs, linked from the setting, describing how to safely disable this option.
=> docs: Document how to use a distinct output base

package.json, src/bazel/bazel_utils.ts
By showing a welcome view, we draw more attention to the "Refresh Target List" command. The "Refresh" command might otherwise be overlooked, in particular by newcomers to this extension which might be particularly prone to an empty build target list.
=> fix: Add a welcome view to the Bazel Build Targets tree view

.bazelci/presubmit.yml, .prettierignore, eslint.config.js, package-lock.json, package.json, src/completion-provider/bazel_completion_provider.ts
So far, the code formatting was not checked by the CI. Now it is. To do so, this commit introduces a new `check-format` npm command. I did not use the `eslint-prettier` plugin because the guidance on https://prettier.io/docs/en/integrating-with-linters.html recommends against doing so.
=> ci: Integrate `prettier` formatting

.prettierignore
This changelog is auto-generated by release please and fails prettier checks, so this is now ignored by prettier.
=> ci: Make prettier ignore changelog

src/definition/bazel_goto_definition_provider.ts
=> feat: Cmd-click to jump to a source file from a build rule

src/definition/bazel_goto_definition_provider.ts
So far, the `go_to_definition` provider did not provide a `originSelectionRange`. Hence, VS Code was falling back on its internal tokenization to decide which part of the text to provide the HyperLink for.
For the label "my/package:file.txt", we hence linked `my`, `package`, `file` and `txt` individually, all pointing to the same file.
With this change, we now instead always provide the link on the full label.
=> fix: Link the full label / file name instead of individual components

src/bazel/bazel_info.ts, src/bazel/bazel_query.ts, src/buildifier/buildifier.ts, src/debug-adapter/client.ts, src/extension/command_variables.ts
`await` is more readable than the explicit use of promises. Also, this works towards flipping `strictNullChecks` to true, because TypeScript complains a bit less about the promisified `execFile` than about explicit uses of callbacks and promises.
While at it, this commit also moves the `getBazelInfo` function from `debugger/client.ts` over to the `BazelInfo` class, where it can be more easily reused. This has the nice side-effect, that also this `info` call will now respect any `startupOptions` potentially configured by the user.
=> refactor: Promisify `execFile`

.github/workflows/release-please.yml
I don't want release-please to create any pull requests in my fork. I
guess most other contributors have no use for those pull requests,
either.
=> ci: Don't run release-please in forks

package.json, scripts/test.sh
During the rebase of #366, I accidentally duplicated the `test` key
inside the `scripts` in `package.json`. There was no warning whatsoever
and CI was still green, but didn't actually run the `vscode-test` tests.
This commit fixes the mishap
=> ci: Fix test invocation

src/test-explorer/lcov_parser.ts, test/lcov_parser.test.ts
This commit teaches the LCOV parser to also read branch coverage data.
Works towards #362
=> feat (coverage): Load branch coverage from coverage files

.github/workflows/build.yml, README.md, src/bazel/tasks.ts, src/test-explorer/index.ts, src/test-explorer/lcov_parser.ts, test/lcov_parser.test.ts
Demangle C++ and Rust symbols using `c++filt` and `rustfilt`. We rely on those tools to be installed on the `$PATH`.
I was also considering whether I should compile `c++filt` and / or `rustfilt` to WebAssembly, but decided against it, given that this would make the build much more complicated and it is currently unclear to me whether we will stick with the "traditional" tool chains (npm, webpack, cargo, ...) or if we will pivot to using Bazel.
=> feat(coverage): Demangling C++ & Rust function names in coverage results

src/codelens/bazel_build_code_lens_provider.ts
1. Add a copy target command
2. Remove a repetitive target name in a command list:
=> feat(codelens) Add a copy target command

src/codelens/bazel_build_code_lens_provider.ts
Current codlens commands look like:
=> feat(codelens): Skip target names for one line targets

src/bazel/tasks.ts
Currently, commandArgs is only applied to debug, test and coverage targets, not run targets, which is inconsistent: clicking a "build" codelens for a component and then clicking a "run" codelens for a runnable target which depends on that component ends up rebuilding it with a different configuration (e.g debug/optimized, remote/local build). It would be much more consistent if commandArgs applied to run targets.
This fixes #394.
=> fix(codelens): Apply commandArgs to run targets

README.md, package.json
Hello, docs lead for pigweed.dev here. We're using your extension in an upcoming tutorial. Labeling this UI as `Bazel Build Targets` might give some the impression that this UI is only used for building binaries (or apps or whatever), when in reality we do a lot of things through this UI: run tests, flash binaries to devices, connect to a device over a console, etc. I think renaming to the more general `Bazel Targets` will therefore make it easier for people to grok that you can do lots of other things through this UI, so long as there's a Bazel target for it.
You all are welcome to change it to something else if you don't like `Bazel Targets`, my main feedback is to just drop the `Build` part from the label. I understand that the meaning here was probably "Targets From The Bazel Build …
=> fix: Change explorer UI label to "Bazel Targets"

src/bazel/tasks.ts, src/test-explorer/index.ts, src/test-explorer/lcov_parser.ts
Rules under repo local_repository() are external repo but symlinked to a local path, usually in the same workspace.
No matter if the local path is in the same workspace, the users should usually want to check the local path specified in local_repository rules instead of the path in bazel output
(`<bazel workspace>/bazel-<repo>/external/...`) in
file explorer.
Works towards #416. Improves #362.
=> fix(coverage): Expand external local repo in coverage report

src/extension/extension.ts, src/workspace-tree/bazel_workspace_tree_provider.ts
Less dependency for BazelWorkspaceTreeProvider, making the future testing changes simpler.
Also small clean ups for this capturing and making the styles (naming and initializations) like
https://github.com/microsoft/vscode-extension-samples/blob/2f83557/tree-view-sample/src/nodeDependencies.ts
=> refactor(workspace-tree): Refine event and dispose handling

.vscode/launch.json
So that we can easily debugging the test cases.
Referencing https://github.com/microsoft/vscode-test-cli/tree/ca11885/?tab=readme-ov-file#debugging
=> chore(debug): Launch Extension Tests with Debug Server

src/extension/extension.ts, src/extension/resources.ts, src/workspace-tree/bazel_package_tree_item.ts, src/workspace-tree/bazel_target_tree_item.ts, src/workspace-tree/bazel_tree_item.ts, src/workspace-tree/bazel_workspace_folder_tree_item.ts, src/workspace-tree/bazel_workspace_tree_provider.ts, src/workspace-tree/icons.ts, test/resources.test.ts
Current resource path resolution is using the source file as the base directory, this would fail if we minify the package into single js.
Use extension path as the base directory is more reliable: it is also working for the current packaging, and we just have to make sure the resource layout of the minified package remains the same.
An enum is provided with a test looping through all value and checking the existence of the icon files in extension.
=> refactor(workspace-tree): Future proof icon path resolution

package.json, src/extension/extension.ts
This option is useful to see messages passed between VS and LSP server to debug issues in LSP server implementations.
Similar functionality is for many other languages, see e.g. previous changes for go and rust:
https://github.com/golang/vscode-go/commit/70e7c4bd3ac06de9f9b4cdeac88ce8681f60ab52
https://github.com/rust-lang/rust-analyzer/pull/302/files
=> feat(lsp): Add option to trace LSP communication

scripts/build.sh, src/debug-adapter/client.ts
This PR fixes starlark debugging which is broken in release 0.11.0 [#432](https://github.com/bazel-contrib/vscode-bazel/issues/432). The debugger program currently fails to start because it can't import vscode. In addition, it also fixes hovering over symbols with starlark debugger respond with errors because symbols are not defined.
=> fix: fix starlark debugger broken in release 0.11.0 (#432)

src/definition/bazel_goto_definition_provider.ts, src/extension/extension.ts
Putting my code where my mouth is:
https://github.com/bazel-contrib/vscode-bazel/issues/430
This feature will allow us to add links to documents, and tool output which jumps to specific  targets, reducing friction and wasted time.
URI handler works such that:
[vscode://bazelbuild.vscode-bazel//my/path/to/tests:target](vscode://bazelbuild.vscode-bazel//my/path/to/tests:target)
(unfortunately github itself won't link out to non-http urls)
Will jump to said target given vscode is opened to a workspace which contains a bazel workspace with that target as the first `workspaceFolder`
I imagine we could handle more situations like:
vscode://bazelbuild.vscode-bazel/fspath/to/workspace//my/path/to/tests:target
or
vscode://bazelbuild.vscode-bazel/test//my/path/to/tests:target
But I imagine anything …
=> feat: URI Handler

package.json, src/extension/extension.ts
This adds an extra configuration option, `bazel.lsp.env`, which passes extra environment variables to the language server. This is useful to enable logging, for example.
=> feat(lsp): Allow passing environment variables to the language server

src/extension/extension.ts
Instantiating and refreshing the `CompletionItemProvider` is very expensive with large repos, due to it querying all targets from the repo. When using a language server the `CompletionItemProvider` is not even registered, so we avoid instantiating and refreshing it in this case.
Relates to #395.
=> fix: Don't instantiate CompletionItemProvider when using a language server

README.md, package.json, src/extension/bazel_wrapper_commands.ts, src/workspace-tree/bazel_target_tree_item.ts, test/BUILD, test/go_to_build_file.test.ts, test/go_to_label.test.ts
This changes the terminology used in various commands from "go to" to "jump". This terminology is already used all over vscode, whereas jump is not. This was agreed in #463.
=> fix: Use "go to" instead of "jump"

package.json, src/codelens/bazel_build_code_lens_provider.ts, src/extension/bazel_wrapper_commands.ts, src/extension/extension.ts, test/bazel_workspace/pkg1/BUILD, test/bazel_workspace/pkg1/main.py, test/bazel_workspace/pkg1/subfolder/lib.py, test/copy_label_to_clipboard.test.ts
This PR adds the already existing (but hidden) command to the command palette to make it usable interactively.
To use it, place your cursor onto a label string inside an open text file.
If the string can be interpreted as a bazel label, the full label is formed and copied to the clipboard.
Part of #194
=> feat(navigation): Add 'Copy Label To Clipboard' to command palette

src/codelens/bazel_build_code_lens_provider.ts, test/code_lens_provider.test.ts
This change modifies the BazelBuildCodeLensProvider to sort targets by the
length of their names (shortest first) before displaying them in the codelens
menu.
The motivation is to provide a more predictable and user-friendly experience
when working with macros in BUILD files. When a macro generates multiple
targets, the main target (which typically has the shortest name) will now
consistently appear first in the codelens menu, while helper targets
(which usually have longer names with suffixes) will appear afterward.
This is particularly useful in scenarios where a macro generates both a main
target and several internal helper targets, as it ensures the most relevant
target is always presented first to the user.
Part of #300
=> feat(codelens): Sort Bazel build targets by name length in codelens
