bazel-contrib/vscode-bazel

- package.json
- src/bazel/tasks.ts
- src/extension/extension.ts
> Add "Bazel: Clean" command.

- .bazelci/presubmit.yml
I'll add the `npm` commands later; I just want to get the most basic configuration in place so I can iterate on it.
> Initial Buildkite CI setup for vscode-bazel.

- src/bazel/bazel_query.ts
- src/workspace-tree/bazel_package_tree_item.ts
- src/workspace-tree/bazel_workspace_folder_tree_item.ts
Package were already sorted.
Fixes #50
> Sort the target names in the tree view.

- package-lock.json
Looks like the versions got out of sync between the two files?  No idea if that's an issue or not, but just running install triggers this to be updated.
> Just run `npm install`

- package-lock.json
- package.json
`npm install` was reporting:
```
found 4 vulnerabilities (1 low, 1 moderate, 2 high)
```
And `npm audit` reported:
```
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ vscode [dev]                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ vscode > gulp-untar > tar …
```
> Run `npm audit fix` to update deps.

- .vscode/extensions.json
- CONTRIBUTING.md
> Update the tslint extension to the new/official one.

- src/buildifier/buildifier.ts
We were treating the syntax error exit code as a "permitted success" for linting, but this was also applying to formatting. So stdout was coming back empty and we were blinding setting the editor content to that.
Fixes #116.
> Don't wipe out the editor when formatting if the file has syntax errors.

- README.md
That way a PR that fails won't appear to make things red.
> Show the badge just for master.

- package.json
added ".star" to the extensions
related issue : https://github.com/bazelbuild/vscode-bazel/issues/127
> added .star to extensions

- package-lock.json
- package.json
> Update deps (`npm update`).

- src/bazel/bazel_command.ts
- src/bazel/bazel_query.ts
- src/bazel/bazel_utils.ts
- src/bazel/tasks.ts
- src/buildifier/buildifier.ts
- src/buildifier/buildifier_format_provider.ts
- src/extension/configuration.ts
- src/extension/extension.ts
There was a mix of styles doing it, so be more consistent.
> Move to get<>() for loading configuration info.

- src/workspace-tree/bazel_workspace_tree_provider.ts
- Cache the scan incase the TreeView asks for the root things again.
- List for changes to the VSCode workspace folders and refresh to reflect
when things are added/removed from a code-workspace.
> Better updating with the tree provider.

- CONTRIBUTING.md
> Expand the contributing some to point to the vscode docs.

- src/debug-adapter/client.ts
> Move off split to handle Windows paths.

- README.md
One of the features of the plugin is syntax highlighting but is not mentioned in the
list of features.
> Mention syntax highlighting as a feature

- .vscode/tasks.json
These are changes VSCode (v1.70.2) wants to make automatically when opening the project.
> Update tasks.json to version 2.0.0

- package.json
See https://bazel.build/external/migration#:~:text=in%20WORKSPACE%2C-,WORKSPACE.bzlmod,-and%20each%20Bazel
> Identify WORKSPACE.bzlmod as Starlark

- src/codelens/bazel_build_code_lens_provider.ts
>  Add "Run" command to binary targets in Codelens

- src/bazel/bazel_command.ts
Reverts bazelbuild/vscode-bazel#322 per https://github.com/bazelbuild/vscode-bazel/pull/322#pullrequestreview-1794785658.
@jfirebaugh PTAL.
> Revert "Prevent automatic MODULE.bazel file creation"

- package-lock.json
- package.json
This allows using the latest version of vscode-languageclient in #317.
> Upgrade typescript to 5.3.3

- CODEOWNERS
> chore: Add @vogelsgesang to CODEOWNERS

- src/codelens/bazel_build_code_lens_provider.ts
Previously, `_binary` targets could only be run, `_test` taregets could only be tested, and all other targets could only be built. This change allows all targets to be built and all non-`_library` targets to be run.
Additionally, this change shortens the names of the targets in codelens, as otherwise the additional commands caused a lot of clutter: `Run //foo/bar/baz:flubber  Build //foo/bar/baz:flubber` etc.
Example after change:
> feat: Extend CodeLens to build and run more targets

- README.md
Add mention of new URI Handler
> docs: Update README.md to mention URI Handler
